# This is a sample conda recipe, which is used for testing features
# in the conda build command.

package:
  name: chirp
  version: 1.2.2

build:
  number: 0
  entry_points:
    - chirpgui = chirp.gui.chirpgui:main
    - cpitch = chirp.pitch.tracker:cpitch
    - cplotpitch = chirp.misc.plotpitch:main
    - ccompare = chirp.compare.ccompare:main
    - csplit = chirp.split.csplit:main
    - cpitchstats = chirp.misc.pitchstats:main

source:
  git_url: git@github.com:dmeliza/chirp.git
  git_tag: 1.2.2

requirements:
  build:
    - python
    - setuptools
    - wxpython
    - numpy
  run:
    - python
    - setuptools
    - numpy
    - wxpython
    - libtfr
    - shapely
    - ewave
    - matplotlib

test:
  requires:
    - nose
  commands:
    - nosetests

about:
  home: https://github.com/melizalab/chirp
  license: GPL
  summary: 'GUI and commandline tool for bioacoustic analysis'

